name: chronosense
description: "Minovi - Understand your time. Reflect on your hours. Live intentionally."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.2.1
  riverpod_annotation: ^4.0.2
  go_router: ^17.1.0
  sqflite: ^2.4.2
  path: ^1.9.0
  shared_preferences: ^2.3.4
  flutter_local_notifications: ^20.1.0
  timezone: ^0.10.1
  intl: ^0.20.1
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.11.1
  riverpod_generator: ^4.0.3
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true
  image_path: "assets/icon/app_icon.png"
  image_path_ios: "assets/icon/app_icon_ios.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon_adaptive.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
